# -*- coding: utf-8 -*-
"""Corea19-seoul.ipynb의 사본의 사본

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DlrESiVQXT01FRH19buOsHZNCBLgenLr
"""

import pandas as pd
import plotly.graph_objs as go
import plotly.offline as py
from fbprophet import Prophet
from fbprophet.plot import plot_plotly, add_changepoints_to_plot

from google.colab import files
files.upload()

df = pd.read_csv('seoul4.csv')

df.head()



fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x=df.date_,
        y=df.confirmed2,
        name='Confirmed in Korea'
    )
)

df_prophet = df.rename(columns={
    'date_': 'ds',
    'confirmed2': 'y'
})

df_prophet.head()

m = Prophet(
    yearly_seasonality=False,
    weekly_seasonality=False,
    daily_seasonality=True,
    seasonality_mode = 'additive'
)

m.fit(df_prophet)

future = m.make_future_dataframe(periods=7)

future.tail(7)

forecast = m.predict(future)

forecast[['ds','yhat','yhat_lower','yhat_upper']].tail(7)

fig = plot_plotly(m,forecast)
py.iplot(fig)

m = Prophet(
    changepoint_prior_scale=0.2,
    changepoint_range=0.98,
    yearly_seasonality=False,
    weekly_seasonality=False,
    daily_seasonality=True,
    seasonality_mode = 'additive'
)

m.fit(df_prophet)

future = m.make_future_dataframe(periods=7)
forecast = m.predict(future)

fig = plot_plotly(m,forecast)
py.iplot(fig)

fig = m.plot(forecast)
a = add_changepoints_to_plot(fig.gca(),m,forecast)

